-- CLEAR EXISTING DATA --

DELETE FROM ExerciseMuscle;
DELETE FROM Muscle;
DELETE FROM Exercise;

-- INSERT DATA --

-- MUSCLES --

SET IDENTITY_INSERT Muscle ON

INSERT INTO Muscle(Id, Name)
VALUES (100, 'CHEST')

INSERT INTO Muscle(Id, Name)
VALUES (200, 'BICEPS')

INSERT INTO Muscle(Id, Name)
VALUES (300, 'TRICEPS')

INSERT INTO Muscle(Id, Name)
VALUES (400, 'QUADRICEPS')

INSERT INTO Muscle(Id, Name)
VALUES (500, 'CALVES')

INSERT INTO Muscle(Id, Name)
VALUES (600, 'SHOULDERS')

INSERT INTO Muscle(Id, Name)
VALUES (700, 'LATS')

INSERT INTO Muscle(Id, Name)
VALUES (800, 'UPPER BACK')

INSERT INTO Muscle(Id, Name)
VALUES (900, 'MID BACK')

INSERT INTO Muscle(Id, Name)
VALUES (1000, 'HAMSTRINGS')

SET IDENTITY_INSERT Muscle OFF

-- EXERCISES --

SET IDENTITY_INSERT Exercise ON

INSERT INTO Exercise(Id, Name)
VALUES (100, 'BARBELL BENCH PRESS')

INSERT INTO Exercise(Id, Name)
VALUES (200, 'DUMBBELL BENCH PRESS')

SET IDENTITY_INSERT Exercise OFF

-- EXERCISE-MUSCLE --

INSERT INTO ExerciseMuscle
VALUES (100, 100)

INSERT INTO ExerciseMuscle
VALUES (100, 300)